# Generated by Django 6.1.1 on 2026-09-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
