# Generated by Django 6.1.1 on 2026-10-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_enquiry_enquiry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='fee',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
