# Generated by Django 6.1.1 on 2026-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_fee_delete_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_marathi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marathi Name'),
        ),
    ]
