# Generated by Django 6.1.1 on 2026-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_name_marathi'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN Card'), ('voter', 'Voter ID'), ('passport', 'Passport'), ('income', 'Income Certificate'), ('caste', 'Caste Certificate'), ('domicile', 'Domicile Certificate'), ('nationality', 'Nationality Certificate'), ('age', 'Age Certificate'), ('ews', 'EWS Certificate'), ('non-creamy', 'Non-Creamy Layer'), ('minority', 'Minority / Alpabhudharak'), ('women', 'Women Reservation'), ('farmer', 'Farmer Certificate'), ('bhumihin', 'Bhumihin Certificate'), ('ration', 'Ration Card'), ('eshram', 'E-Shram Card'), ('holding', '7/12 Holding'), ('crop', 'Crop Insurance'), ('shop', 'Shop Act / Udyog'), ('food', 'Food License'), ('gazette', 'Gazette'), ('driving', 'Driving Licence'), ('other', 'Other')], default='other', max_length=50, verbose_name='Service Category'),
        ),
    ]
