"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z_5*&^vst6n=%@!zrx@+%bk0*-o!_rtez55#%4xb6^m@spnb_-'

 

# ============================================
# SECURITY SETTINGS
# ============================================

# DEBUG — development me True, LIVE me False
DEBUG = True  # ← Deploy ke baad False karna

# Allowed hosts
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    # Deploy ke baad domain add karna:
    # 'mahaesevakendra.in',
    # 'www.mahaesevakendra.in',
]

# ============================================
# SECURITY HEADERS
# ============================================

# XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Content type sniffing prevent
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# Referrer policy
SECURE_REFERRER_POLICY = 'same-origin'

# ============================================
# SESSION SECURITY
# ============================================

# Session cookie HTTP only
SESSION_COOKIE_HTTPONLY = True

# Session 1 hour me expire
SESSION_COOKIE_AGE = 3600

# Browser band hone pe session expire
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ============================================
# HTTPS/SSL — LIVE hone ke baad True karna
# ============================================

SECURE_SSL_REDIRECT = False  # ← Live pe True
SESSION_COOKIE_SECURE = False  # ← Live pe True
CSRF_COOKIE_SECURE = False  # ← Live pe True
SECURE_HSTS_SECONDS = 0  # ← Live pe 31536000 (1 year)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # ← Live pe True
SECURE_HSTS_PRELOAD = False  # ← Live pe True

 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'services',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
